### ISSUE TITLE
Include `redirectUri` in `DispatchOutcome.VerifierResponse.Rejected`

### ISSUE THREAD

**Issue by dzarras** [eu-digital-identity-wallet/eudi-lib-jvm-siop-openid4vp-kt#172]
`DispatchOutcome.VerifierResponse.Rejected` must be updated to a data class that contains an nullable property `redirectUri` similar to `DispatchOutcome.VerifierResponse.Accepted`.

Even in the case that the user didn't give his consensus to present a credential, the verifier might want to be redirect to a certain uri to display extra information to the user.

**Comment by dzarras** [comment]
@babisRoutis I was reading the spec again. I believe that `redirect_uri` is applicable only during the happy path. 

In [6.2.Response Mode "direct_post"](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#name-response-mode-direct_post), `redirect_uri` is defined as an optional property returned by the Verifier Endpoint once it has successfully processed the response provided by the Wallet.
Quoting:

>If the Response Endpoint has successfully processed the request, it MUST respond with HTTPS status code 200. The following new parameter is defined for use in the response from the endpoint:
>`redirect_uri`: OPTIONAL. When the redirect parameter is used the Wallet MUST send the User Agent to this redirect URI. The redirect URI  allows the Verifier to continue the interaction with the End-User on the device where the Wallet resides after the Wallet has sent the Authorization Response to the Response URI. It especially enables the Verifier to prevent session fixation ([Section 12.2](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#session_fixation)) attacks.

My initial concern still stands though. The Verifier might want to present some extra information to the User in case the response provided by the Wallet has not been successfully processed or has been rejected.

For this we can leverage the fact that OpenId4VP is an extension of OAuth2. 
Checking [6.4. Error Response](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#name-error-response) we read:
> The error response follows the rules as defined in [[RFC6749](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#RFC6749)], with the following additional clarifications.

Checking [RFC6749: 5.2 Error Response](https://www.rfc-editor.org/rfc/rfc6749.html#section-5.2) we read:
> The authorization server responds with an HTTP 400 (Bad Request) status code (unless specified otherwise) and includes the following parameters with the response.

The parameter that stands out is `error_uri` which is defined as follows:
> `error_uri`: OPTIONAL.  A URI identifying a human-readable web page with information about the error, used to provide the client developer with additional information about the error. Values for the "error_uri" parameter MUST conform to the URI-reference syntax and thus MUST NOT include characters outside the set %x21 / %x23-5B / %x5D-7E. 

This seems to be a good candidate. What do you think?

**Comment by babisRoutis** [comment]
@dzarras We can watch https://github.com/openid/OpenID4VP/issues/137
