### ISSUE TITLE
ISO18013-7 Missing `apu` parameter from JWE Header of JARM

### ISSUE THREAD

**Issue by babisRoutis** [eu-digital-identity-wallet/eudi-lib-jvm-siop-openid4vp-kt#177]
ISO18013-7 (dts draft2) requires that

> The mdoc shall set the apu JWT (JWE) header parameter to the base64url-encoded-with-no-padding
value of the mdocGeneratedNonce of the SessionTranscript as defined in Section B.4.4.

Currently, library doesn't set this parameter

**Comment by babisRoutis** [comment]
The actual problem is that `apv` & `apu` are `mso_mdoc` specific parameters.
With the current version of the library the following problems are present:
- We set `apv` always regardless whether we have a presentation related to `mso_mdoc` or some other format.
- We don't have defined a way to get from the wallet the `apu` parameter

A solution to both problems would be to redefine the `VpToken` which currently is an alias to `String` as a sealed interface with two members:
- `Generic(value: String)` This can be used in simple cases were vp_token is just a string
- `MsoMdoc(value: String, apu: String)` This would be used in case of `msd_mdoc` related presentation

With this approach: `apv` & `apu` can only be set in encrypted responses, in case we are working with `mso_mdoc`

**Comment by babisRoutis** [comment]
@marinaioannou From caller's perspective, do you see any problem with the proposed solution?

On the caller's site the difference would be that 
instead of passing the `vp_token` as a String, you would need to wrapped inside `VpToken.MsoMdoc` structure and include the `apu` (encoded) that you calculate

**Comment by marinaioannou** [comment]
@babisRoutis I agree with the proposed solution.
