### ISSUE TITLE
OpenID4VP draft 20 path formatting

### ISSUE THREAD

**Issue by ivan770** [eu-digital-identity-wallet/eudi-lib-jvm-siop-openid4vp-kt#210]
Hi!

While trying to use the [web verifier app](https://verifier.eudiw.dev/) I noticed that it generates presentation requests according to the [OpenID4VP draft 18](https://openid.net/specs/openid-4-verifiable-presentations-1_0-ID2.html#name-presentation-request-4), with paths formatted like so: `$.mdoc.field`.

[Draft 20](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#name-presentation-request-4), which is linked in the project README file specifies that paths have to be formatted in a different manner, with namespace qualification: `$[namespace][field]`.

**Comment by dzarras** [comment]
@babisRoutis @vafeini Since this relates to eu-digital-identity-wallet/eudi-web-verifier#33, shouldn't we either close this issue or move it to [eu-digital-identity-wallet/eudi-web-verifier](https://github.com/eu-digital-identity-wallet/eudi-web-verifier) for better tracking?

**Comment by vafeini** [comment]
@ivan770 Closing this one as the same is discussed [here](https://github.com/eu-digital-identity-wallet/eudi-web-verifier/issues/33)
