### ISSUE TITLE
Client MetaData should be optional while processing an Authorization Request Object

### ISSUE THREAD

**Issue by ydanneg** [eu-digital-identity-wallet/eudi-lib-jvm-siop-openid4vp-kt#211]
The problem:
`RequestObjectResolver` always resolves (checkNotNull) and validates verifier's `clientMetadata` that is used to build jarmRequirement.
It conflicts with `ValidatedRequestObject` model, where `clientMetaDataSource` is an optional, which is correct (follows specs, see bellow).

Documentation:
https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#name-authorization-request
> client_metadata: 
> OPTIONAL. A JSON object containing the Verifier metadata values. It MUST be UTF-8 encoded. It MUST NOT be present if client_metadata_uri parameter is present.
> 
> client_metadata_uri: 
> OPTIONAL. A string containing an HTTPS URL pointing to a resource where a JSON object with the Verifier metadata can be retrieved. The scheme used in the client_metadata_uri value MUST be https. The client_metadata_uri value MUST be reachable by the Wallet. It MUST NOT be present if client_metadata parameter is present.
> 

https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#name-signed-and-encrypted-respon
> To sign, or sign and encrypt the Authorization Response, implementations MAY use JWT Secured Authorization Response Mode for OAuth 2.0 (JARM) [[JARM](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#JARM)].

Possible resolution:
- Do not resolve `clientMetadata` if it doesn't exist.
- Do not build `jarRequirements` If `clientMetaData` doesn't exist

**Comment by babisRoutis** [comment]
Hi @ydanneg 

Thanks for reporting this. 

I find that the specification is not totally precise. 
Client metadata (either by value or by reference) are not totally optional. 
For instance in case response mode is `direct_post.jwt` (or similar *.jwt)  metadata should be provided.

 Your point though about the implementation is correct.
