### ISSUE TITLE
Unable to serialize ResolvedRequestObject

### ISSUE THREAD

**Issue by ydanneg** [eu-digital-identity-wallet/eudi-lib-jvm-siop-openid4vp-kt#217]
It is currently unable to serialize [ResolvedRequestObject](https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-siop-openid4vp-kt/blob/a10fbaa3f293b5b604ba71f4c2b5a4270cdbc1e5/src/main/kotlin/eu/europa/ec/eudi/openid4vp/AuthorizationRequestResolver.kt#L29).

All models that are defined in [here](https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-siop-openid4vp-kt/blob/a10fbaa3f293b5b604ba71f4c2b5a4270cdbc1e5/src/main/kotlin/eu/europa/ec/eudi/openid4vp/AuthorizationRequestResolver.kt ) are Serializable.
But PresentationDefinition is coming from another library [eudi-lib-jvm-presentation-exchange-kt](https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-presentation-exchange-kt/blob/1fda3e49fd5b3f6afd0d1fb4145f82826d9d701a/src/main/kotlin/eu/europa/ec/eudi/prex/Types.kt#L347) which is not Serializable.

The use case for serialization is simple:
- Between getting the Authorization Request and sending an Authorization Response user consent is required. Before asking the user consent client implementations could serialize data and then deserialize it to continue the flow.

Currently it is not possible.

Unit test: https://gist.github.com/ydanneg/3f24f7d0a1ec8eeb9511f968fc4b4c86

**Comment by ydanneg** [comment]
One approach would be to make all types defined [here](https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-presentation-exchange-kt/blob/1fda3e49fd5b3f6afd0d1fb4145f82826d9d701a/src/main/kotlin/eu/europa/ec/eudi/prex/Types.kt) to be Serializable

**Comment by babisRoutis** [comment]
Hi @ydanneg 

Yes, you are absolute right, both for the problem and for the solution.
Opened https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-presentation-exchange-kt/issues/137 to fix this in the presentation exchange library and then provide an update version for vp.

Thanks for this
