### ISSUE TITLE
ISO 18013-7 apv JWE header parameter

### ISSUE THREAD

**Issue by marinaioannou** [eu-digital-identity-wallet/eudi-lib-jvm-siop-openid4vp-kt#232]
_Documentation:_ 
According to the ISO 18013-7:
> The mdoc shall set the apv JWT (JWE) header parameter to the base64url-encoded-with-no-padding value of the nonce Authorization Request parameter from the Authorization Request Object.

_The problem:_ 
Currently, the `apv` has the value of `nonce` Authorization Request parameter from the Authorization Request Object and not the base64url-encoded-with-no-padding value of it.

_Proposed resolution:_ 
Please consider replacing in the [line ](https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-siop-openid4vp-kt/blob/dd1d3ed216a1be6ea9ae1ff2336aa2dc25328f60/src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/JarmJwt.kt#L86):
`Base64URL(data.nonce)` with `Base64URL.encode(data.nonce)`

**Comment by babisRoutis** [comment]
@dzarras Please prepare a fix for this & in addition check whether it affects verifier-endpoint

**Comment by babisRoutis** [comment]
@marinaioannou Thanks for reporting this. Good catch!

**Comment by dzarras** [comment]
@babisRoutis / @vafeini Shouldn't we also be similarly setting the `apv` JWE header claim when doing both signature and encryption as well?

I'm referring to https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-siop-openid4vp-kt/blob/dd1d3ed216a1be6ea9ae1ff2336aa2dc25328f60/src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/JarmJwt.kt#L105
