### ISSUE TITLE
Self Signed Certificates

### ISSUE THREAD

**Issue by icarboneaq** [eu-digital-identity-wallet/eudi-lib-jvm-siop-openid4vp-kt#287]
Hello, I'm attempting to issue and verify MDOC credentials besides MDL and am running into an issue around verifying the cert chain that is passed in the JWT's header during the OpenID4VP process. For the purposes of testing I am using self signed certificates that chains up to an untrusted root, and the service is expectedly throwing an 'Untrusted x5c' error.

It appears that the issue comes from [here](https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-siop-openid4vp-kt/blob/d6fa3a98629932449c73b726ecc140088c3ebb08/src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/RequestAuthenticator.kt#L185). Are there any plans to support self signed certificates in this way? I found some code in the EUDI demo wallet that allows for support of self signed certificates served by web servers, but not for this specifically.

**Comment by babisRoutis** [comment]
Hi @icarboneaq 

Please take a look in `Example.kt` located under the tests folder.

Actually, you can pass as a parameter to the configuration (`SiopOpenId4VpConfig`) an implementation of the trust interface.

[Here](https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-siop-openid4vp-kt/blob/d6fa3a98629932449c73b726ecc140088c3ebb08/src/test/kotlin/eu/europa/ec/eudi/openid4vp/Example.kt#L64) you can find an example that trusts any issuer certificate (chain). Of course it shouldn't be used in production
